//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using System.Collections;
using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Text;
using System.Security.Cryptography.X509Certificates;
using System.IO;
using System.Threading;
namespace NPL
{
    public class SSLSender
    { 
        public SSLSender()
        {
        }public static void sendmessage(){
            Console.WriteLine(0);
           var client = new UdpClient();
            Thread.Sleep(100);
            IPEndPoint ep = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 11000); // endpoint where server is listening
            client.Connect(ep);

// send data
            byte[] message = Encoding.UTF8.GetBytes(MainWindow.GetLocalIPAddress()+"<EOF>");
            client.Send(message,12);

// then receive data
            var receivedData = client.Receive(ref ep);
            Console.WriteLine( System.Text.Encoding.UTF8.GetString(receivedData));
        }
    
    }
}

